immutable/contracts

contracts/royalty-enforcement/RoyaltyAllowlist.sol
PR addresses internal audit which seperates proxy implementations into its own mapping.
=> [SMR-1009] Audit

contracts/royalty-enforcement/RoyaltyAllowlist.sol, contracts/token/erc721/abstract/ImmutableERC721Base.sol, contracts/token/erc721/abstract/ImmutableERC721RoyaltyEnforced.sol, test/token/erc721/ImmutableERC721PermissionedMintable.test.ts
Addresses internal audit from: https://immutable.atlassian.net/wiki/spaces/~63ef260d7e8114bf5b279556/pages/2138735967/Internal+Contract+Audit+zkEVM+Contracts
=> NOJIRA - internal audit fixes

CODEOWNERS
Adding global file glob to match all files to immutable/assets GitHub team.
=> feature: add CODEOWNERS to root

.github/workflows/test.yml, foundry.toml
Introducing forge tests for bridge contracts.
Adding forge test workflow to CI.
=> [NOJIRA] Add forge test to test.yml

contracts/token/erc721/abstract/ERC721HybridPermit.sol, contracts/token/erc721/preset/ImmutableERC721.sol, contracts/token/erc721/preset/ImmutableERC721MintByID.sol, package.json, test/allowlist/AllowlistERC721TransfersApprovals.test.ts, test/allowlist/HybridApproval.test.ts, test/allowlist/OperatorAllowlist.test.ts, test/royalty-enforcement/RoyaltyMarketplace.test.ts, test/token/erc721/ImmutableERC721.test.ts, test/token/erc721/ImmutableERC721HybridPermit.test.ts, test/token/erc721/ImmutableERC721MintByID.test.ts, test/token/erc721/ImmutableERC721MintByIDPermit.test.ts, test/utils/DeployHybridFixtures.ts, test/utils/DeployRegularFixtures.ts, tsconfig.json
Line coverage updated to 100% for contracts:
- `MintingAccessControl.sol`
- `ImmutableERC721MintByID.sol`
- `ImmutableERC721MintByID.sol`
- `ImmutableERC721Base.sol`
- `ImmutableERC721HybridBase.sol`
=> [GMS-1106] Increase test coverage

contracts/bridge/x/README.md
Add a `README.md` to `contracts/bridge/x` that documents addresses for Immutable smart contracts.
=> [DX-2440] Add immutable X contract addresses readme

clients/erc721.ts
Basic fixes discussed in this thread: https://imtbl.slack.com/archives/C03KPP6T55Y/p1699422994834329
=> Fixed domain method calls to connect to provider & use empty call override params

contracts/token/erc721/abstract/ERC721Hybrid.sol, contracts/token/erc721/abstract/ERC721HybridPermit.sol, contracts/token/erc721/abstract/ERC721Permit.sol, contracts/token/erc721/abstract/IERC4494.sol, contracts/token/erc721/abstract/ImmutableERC721Base.sol, contracts/token/erc721/abstract/ImmutableERC721HybridBase.sol, contracts/token/erc721/abstract/MintingAccessControl.sol, contracts/token/erc721/erc721psi/README.md, contracts/token/erc721/preset/ImmutableERC721.sol, contracts/token/erc721/preset/ImmutableERC721MintByID.sol
changes done according to: https://docs.google.com/document/d/1uaPqJe2aEji3PXJM4OXiNMB64HtE9Xgw-S2ONNg8Kbg/edit
=> [GMS-1271] Audit recs for ImmutableERC721

contracts/allowlist/IOperatorAllowlist.sol, contracts/allowlist/OperatorAllowlist.sol, contracts/allowlist/OperatorAllowlistEnforced.sol, contracts/allowlist/README.md
Checklist in JIRA: https://immutable.atlassian.net/browse/GMS-1284
Related to https://github.com/immutable/contracts/pull/139/files
=> [GMS-1284] Audit recommendations for OperatorAllowlist contracts

script/bridge/x/v4/DeployRegistrationV4.s.sol, script/bridge/x/v4/DeployRegistrationV4Dev.s.sol, script/bridge/x/v4/DeployRegistrationV4Sandbox.s.sol, test/bridge/x/v4/RegistrationV4.t.sol
- These scripts are intended to facilitate deployments across the dev, sandbox and prod environments.
Resolves: [CORE-2047]
[CORE-2047]: https://immutable.atlassian.net/browse/CORE-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add mainnet and sandbox deployment scripts

contracts/bridge/x/v4/README.md
- Updated x/bridge/v4 docs covering RegistrationV4 contract addresses
=> Update RegistrationV4 contracts (sandbox and mainnet)

contracts/trading/seaport/ImmutableSeaport.sol, contracts/trading/seaport/conduit/ConduitController.sol, contracts/trading/seaport/interfaces/ImmutableSeaportEvents.sol, contracts/trading/seaport/validators/ReadOnlyOrderValidator.sol, contracts/trading/seaport/validators/SeaportValidator.sol, contracts/trading/seaport/validators/SeaportValidatorHelper.sol, contracts/trading/seaport/zones/ImmutableSignedZone.sol, contracts/trading/seaport/zones/interfaces/SIP5Interface.sol, contracts/trading/seaport/zones/interfaces/SIP6EventsAndErrors.sol, contracts/trading/seaport/zones/interfaces/SIP7EventsAndErrors.sol, contracts/trading/seaport/zones/interfaces/SIP7Interface.sol, test/seaport/immutablesignedzone.test.ts
Relaxes the `pragma` in trading related contracts to facilitate external use of contracts.
=> [TD-1326] Relax pragma in trading contracts and fix test compilation

README.md
- Add quick links to presets in readme
=> [NO-JIRA]: add quick links in readme

contracts/trading/seaport/zones/immutable-signed-zone/v2/README.md
Update links for Immutable Signed Zone V2 threat model and internal audit docs.
=> [TD-1397] Update links for Immutable Signed Zone V2

README.md
Description
Update example to be consistent with same example in other areas
Resolved issues
Jira: https://immutable.atlassian.net/browse/GMS-1906
=> docs: Normalise code example for preset contract ImmutableERC721

abi/generated.ts, abi/index.ts, wagmi.config.ts
Generate `PaymentSplitter` ABI
=> GMS-1812 PaymentSplitter ABI

contracts/token/erc721/abstract/ImmutableERC721Base.sol
Small PR to fix small issue that someone pointed out.
=> Fix small grammatical issue

contracts/token/erc721/abstract/ERC721HybridV2.sol
=> Add virtual to totalSupply

contracts/staking/README.md
Added test net addresses to the README file
=> Added testnet deployment information for staking contracts

,,.x.txt
Remove file that was mistakenly committed.
=> Remove file that should never have been committed
