.github/dependabot.yml, .gitignore, README.md, package-lock.json, package.json
- Add config to dependabot to ignore major versions
- Update '@types/node' to match lts version
- Update 'typechain', '@typechain/ethers-v5' and '@typechain/hardhat' to match versions used in the sdk
=> GMS-1009: update dependencies

package-lock.json, package.json
`solidity-bits` and `solidity-bytes-utils` are directly imported in contracts, so they must be declared as `dependencies` rather than (currently) `devDependencies` for projects to install correctly.
=> Move `solidity-bits` and `solidity-bytes-utils` to dependencies

.github/workflows/publish.yaml, .gitignore, README.md, clients/erc721-mint-by-id.ts, clients/erc721.ts, clients/index.ts, index.ts, package-lock.json, package.json, tsconfig.json
Background: https://immutable.atlassian.net/wiki/spaces/IGG/pages/2262959181/Moving+Contract+Clients+out+of+SDK
Tested replacing contract client in tmp branch of testing repo: https://github.com/immutable/imx-testing-mr/pull/29/files
=> [GMS-1083] Add contract clients

contracts/token/erc721/abstract/ERC721Hybrid.sol, test/allowlist/HybridApproval.test.ts, test/token/erc721/ImmutableERC721.test.ts, test/token/erc721/ImmutableERC721HybridPermit.test.ts
- Make the name more consistent
=> GMS-1104: Update bulkMintThreshold func name

contracts/bridge/x/Core.sol, contracts/bridge/x/Registration.sol, contracts/token/erc721/x/Asset.sol, contracts/token/erc721/x/IMintable.sol, contracts/token/erc721/x/Mintable.sol, contracts/token/erc721/x/utils/Bytes.sol, contracts/token/erc721/x/utils/Minting.sol, test/token/x/Asset.test.ts
Aims to merge all the contracts used by Immutable X customers into our central contracts repository. Contracts sourced from: 
- https://github.com/immutable/imx-contracts
- https://github.com/immutable/ts-immutable-sdk/tree/main/packages/internal/contracts
=> Migrating all Immutable X contracts and tests

README.md, package.json
1. Do not merge this until, https://github.com/immutable/zkevm-contracts/pull/116 is merged 
2. Also until this repository is renamed from `zkevm-contracts` to `contracts`
=> DX-2420: Updated the package name from zkEVM-contracts to contracts

.env.example, CONTRIBUTING.md, deploy/utils.ts, deploy/x/README.md, deploy/x/asset.ts, hardhat.config.ts, tsconfig.json
Why?
[DX-2440](https://immutable.atlassian.net/browse/DX-2440)
The Asset contract was recently moved into the repo from `imx-contracts` (now deprecated). `imx-contracts` had scripts to deploy the contract which was used in the [NFT minting tutorial](https://docs.immutable.com/docs/x/zero-to-hero-nft-minting/) on the docs website.
The PR adds those deployment scripts to the monorepo so users can continue to use the NFT minting guide with the monorep.
[DX-2440]: https://immutable.atlassian.net/browse/DX-2440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DX-2440] Add Asset contract deployment script for NFT minting guide

contracts/token/erc1155/abstract/ImmutableERC1155Base.sol, contracts/token/erc1155/preset/draft-ImmutableERC1155.sol, test/token/erc1155/ImmutableERC1155.t.sol, test/token/erc1155/ImmutableERC1155Test.t.sol
Adds fields `baseURI` and `contractURI` in order to be compatible with Immutable metadata standards that are consistent with ERC721.
ERC1155 standard contains a `uri` method which acts similar to a baseURI but with ID substitution, for now we are syncing both the `uri` and `baseURI` to be compatible with both approaches.
=> [GMS-1172] Add metadata fields to ERC1155 preset contract

clients/erc20.ts, clients/erc721-mint-by-id.ts
Uses empty objects as default in order to avoid `undefined` being passed to the main function
=> GMS-1207: improves how params are accepts

clients/config/overrides.ts, clients/erc20.ts, clients/erc721-mint-by-id.ts, clients/erc721.ts
- Adds default gas override optiosn to out contract clients
- Spread the defaults first, so that user input overrides can still override
=> [GMS-1265] Add default gas overrides

clients/config/overrides.ts, clients/erc20.ts, clients/erc721-mint-by-id.ts, clients/erc721.ts
Bug raised from [slack thread](https://imtbl.slack.com/archives/C03KPP6T55Y/p1702445529405719)
Possibly [related issue](https://github.com/ethers-io/ethers.js/issues/1144)
**Issue 1**
Contract read functions are being processed as transactions when provided with gas config parameters, causing them to error. 
- Restored read functionality by removing these params
- Verified using local client on random `testnet` collection: `0x2b78f58db10873ba99f7e10ea643c3e232977a00`, output below
```
❯ npm run read
> mycontracts@1.0.0 read
> ./node_modules/.bin/ts-node read.ts
readFunctions()
--> MINTER_ROLE:  0x4d494e5445525f524f4c45000000000000000000000000000000000000000000
--> balanceOf:  3
--> ownerOf:  0x33273ef27D51F2D655c7eC33b66A40137368F5Fd
--> baseURI: …
```
=> [NO-JIRA] Fix client gas config

clients/erc721-mint-by-id.ts, clients/erc721.ts, tsconfig.json
Removes unneeded files from build
exported `dist` folder is much smaller, however does contain the necessary files for generating clients:
```
npm notice 115B   dist/clients/config/overrides.d.ts
npm notice 339B   dist/clients/config/overrides.js
npm notice 2.1kB  dist/clients/erc20.d.ts
npm notice 2.2kB  dist/clients/erc20.js
npm notice 11.5kB dist/clients/erc721-mint-by-id.d.ts
npm notice 13.1kB dist/clients/erc721-mint-by-id.js
npm notice 14.0kB dist/clients/erc721.d.ts
npm notice 15.6kB dist/clients/erc721.js
npm notice 140B   dist/clients/index.d.ts
npm notice 679B   dist/clients/index.js
npm notice 27B    dist/index.d.ts
npm notice 802B   dist/index.js
npm notice 13.1kB dist/typechain-types/@openzeppelin/contracts/token/ERC20/ERC20.d.ts
npm notice 77B …
```
=> [GMS-1325] Remove unnecessary build artefacts

.github/workflows/publish.yaml
Old token will not work with public repos, granular token scoped to single permission set and package
=> Switch to granular scoped token

contracts/trading/seaport/ImmutableSeaport.sol, contracts/trading/seaport/zones/ImmutableSignedZone.sol, test/seaport/immutablesignedzone.test.ts, test/seaport/utils/deploy-immutable-contracts.ts
This PR makes the owner an argument in the constructor to be configurable with `CREATE3` contract deployments.
`Ownable2Step` was replaced with `Ownable` so the ownership could be transferred in a single step during initalization. Our other contracts use `Ownable` so its more standard
=> [TD-1114] Make ImmutableSeaport and ImmutableSignedZone ownership configurable through constructor

.github/workflows/publish.yaml, .github/workflows/test.yml
Use lower network concurrency for improved CI stability. Also introduce flag on publishing which was missing it and therefore failing to run
=> fix: flakey yarn install by reducing network concurrency

package.json, yarn.lock
The `postinstall` step which did cleanup on upstream foundry.toml files was not Windows compatible. This should fix that.
=> fix: use rimraf for OS agnostic postinstall cleanup

CODEOWNERS
- Add code ownership of trading contract to traders team
- Fix code owernership of `test/` directy, which was incorrectly named as `tests/`
=> chore: Add traders code ownership

clients/erc721-mint-by-id.ts, clients/erc721.ts, contracts/allowlist/OperatorAllowlistEnforced.sol, test/allowlist/AllowlistERC721TransfersApprovals.test.ts, test/allowlist/HybridApproval.test.ts, test/royalty-enforcement/RoyaltyMarketplace.test.ts
- Removed ability to update OperatorAllowlistRegistry in OperatorAllowlistEnforced contracts:
- ImmutableERC1155Base
- ImmutableERC721Base
- ImmutableERC721HybridBase
=> [GMS-1362] Remove setOperatorAllowlistRegistry from preset nft contracts

package.json
The previous syntax worked with `npm` but not with `yarn`. Explicitly using `npx` to find the executable should fix the issue
=> fix: npx for correct postinstall exec access

contract_address.json
**Problems to solve**: 
We would like one centralized place, publicly expose key contract addresses, so that we provide both confidence, trust and convenience to the builders and users in the community.
Currently, Immutable teams use Confluence or other alternatives to track deployed and verified contract addresses. They may or may not be up to date. No community members can see them from our public Docs. If they go to our chain exploer, since we deployed same thing multiple times, it's also not easy to see which ones are official.
**Solution**
* 1 json starts with most basic information about each contract that are useful in our ecosystem.
* Merge and publish this list ahead of Mainnet announcement.
* Short term will duplicate this information to a table on …
=> chore: Initial shape of centralized place for all Deployed contract addresses

contracts/games/gems/GemGame.sol, contracts/games/gems/README.md, script/games/gems/DeployGemGame.sol, test/games/gems/GemGame.t.sol
Adds a new contract - `GemGame`.
This contract includes a single function which emits an event. This event is intended to be indexed off-chain.
=> [TP-2147] Add Gem Game contract

contracts/games/gems/GemGame.sol, contracts/games/gems/README.md, script/games/gems/DeployGemGame.sol, test/games/gems/GemGame.t.sol
Adds access control and pausable functionality to the GemGame contract.
This will allow pausing of the contract if we find that it is being abused.
=> Add AccessControl, Pausable to GemGame contract

contracts/trading/seaport/zones/immutable-signed-zone/v2/ImmutableSignedZoneV2.sol, contracts/trading/seaport/zones/immutable-signed-zone/v2/README.md, contracts/trading/seaport/zones/immutable-signed-zone/v2/ZoneAccessControl.sol, contracts/trading/seaport/zones/immutable-signed-zone/v2/interfaces/ZoneAccessControlEventsAndErrors.sol, test/trading/seaport/ImmutableSeaportSignedZoneV2Integration.t.sol, test/trading/seaport/zones/immutable-signed-zone/v2/IImmutableSignedZoneV2Harness.t.sol, test/trading/seaport/zones/immutable-signed-zone/v2/ImmutableSignedZoneV2.t.sol, test/trading/seaport/zones/immutable-signed-zone/v2/README.md
Adds a zone manager role to ImmutableSignedZoneV2.
=> [TD-1396] Add zone manager role to ImmutableSignedZoneV2

audits/trading/202404-threat-model-immutable-signed-zone-v2.md
Threat model for Immutable Signed Zone v2.
=> [TD-1396] Immutable Signed Zone v2 Threat Model

.gitignore, contracts/deployer/AccessControlledDeployer.sol, contracts/deployer/create/OwnableCreateDeploy.sol, test/deployer/AccessControlledDeployer.t.sol, test/deployer/create2/Create2Utils.sol, test/deployer/create2/OwnableCreate2Deployer.t.sol, test/deployer/create3/Create3Utils.sol, test/deployer/create3/OwnableCreate3Deployer.t.sol
The existing `OwnableCreate2Deployer` and `OwnableCreate3Deployer` contracts only allow a single deployer address—the owner—to deploy contracts. There is a need to enhance this so as to allow a set of authorised addresses to deploy contracts. This PR introduces a new contract that forwards deployment requests to the existing Create2 and Create3 deployers while layering role-based access controls to these capabilities. This contract could thus enable more flexible deployment access controls for existing single-owner Create2 and Create3 deployers.
Additional details of this requirement can be found [here](https://immutable.atlassian.net/wiki/spaces/~71202063c6a3620e6b4ab4a8bc3dd0bdfc3297/pages/2504949857/Breaking+up+the+Deployment+Key).
=> Enable more flexible access controls for contract deployment

contracts/allowlist/OperatorAllowlistEnforced.sol, contracts/token/erc1155/abstract/ImmutableERC1155Base.sol, contracts/token/erc721/abstract/ImmutableERC721Base.sol, contracts/token/erc721/abstract/ImmutableERC721HybridBase.sol
- Having AccessControlEnumerable is causing an issue with upgradable ERC721 contracts when they are trying to extend this class.
=> NO-JIRA [fix] remove accesscontrolenumerable from oalenforced

README.md
Fixes `yarn` installation command as `yarn install [PACKAGE]` is no longer available.
=> [TD-1549] Update installation command

abi/generated.ts, contracts/multicall/GuardedMulticaller2.sol, test/multicall/SigUtils.t.sol
There is a typo in `MULTICALL_TYPEHASH` that we should fix. This does not affect the behavior of the contract. It would, however, affect how the signature should be generated off-chain. Considering no one has used the contract, we would prefer to fix this issue.
=> Update GuardedMulticaller2 Multicall Typehash

.github/workflows/publish.yaml, .github/workflows/test.yml, CODEOWNERS
1. Adds [SBOM artifact signing](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds) job as we publish to NPM.
2. Adds [Dependency Review](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review) job that fails on Critical severity findings (Node/JavaScript)
3. Adds Product Security to CODEOWNERS under .github along with the current maintainers (for visibility to job changes)
=> [ITSEC-2280] Add Dependency Review and SBOM signing jobs, update CODEOWNERS

contracts/access/MintingAccessControl.sol, contracts/bridge/x/v4/CoreV4.sol, contracts/deployer/create/OwnableCreateDeploy.sol, contracts/deployer/create2/OwnableCreate2Deployer.sol, contracts/deployer/create3/OwnableCreate3.sol, contracts/deployer/create3/OwnableCreate3Address.sol, contracts/deployer/create3/OwnableCreate3Deployer.sol, contracts/token/erc1155/abstract/ERC1155Permit.sol, contracts/token/erc1155/abstract/ImmutableERC1155Base.sol, contracts/token/erc20/preset/ImmutableERC20MinterBurnerPermit.sol, contracts/token/erc721/abstract/ImmutableERC721Base.sol, contracts/token/erc721/abstract/ImmutableERC721HybridBase.sol, contracts/trading/seaport/zones/immutable-signed-zone/v1/interfaces/SIP5Interface.sol, contracts/trading/seaport/zones/immutable-signed-zone/v1/interfaces/SIP6EventsAndErrors.sol, contracts/trading/seaport/zones/immutable-signed-zone/v1/interfaces/SIP7EventsAndErrors.sol, contracts/trading/seaport/zones/immutable-signed-zone/v1/interfaces/SIP7Interface.sol, contracts/trading/seaport/zones/immutable-signed-zone/v2/interfaces/SIP5Interface.sol, contracts/trading/seaport/zones/immutable-signed-zone/v2/interfaces/SIP6EventsAndErrors.sol, contracts/trading/seaport/zones/immutable-signed-zone/v2/interfaces/SIP6Interface.sol, contracts/trading/seaport/zones/immutable-signed-zone/v2/interfaces/SIP7EventsAndErrors.sol, contracts/trading/seaport/zones/immutable-signed-zone/v2/interfaces/SIP7Interface.sol
Resolve all slither and solhint issues. 
Prepare repo for update requiring all checks to pass prior to PR merge.
=> Resolve solhint and slither issues

.github/workflows/publish.yaml
Similar to https://github.com/immutable/ts-immutable-sdk/pull/2356, adds a note as to the critical code section
> Removing or preventing GitHub from attesting the code will cause a critical security incident - clarify in the comments.
=> Add a security warning

contracts/staking/README.md, contracts/staking/StakeHolder.sol, script/staking/DeployStakeHolder.sol, test/staking/README.md, test/staking/StakeHolderBase.t.sol, test/staking/StakeHolderInit.t.sol, test/staking/StakeHolderOperational.t.sol
This PR addresses internal audit feedback for the staking contract. The changes are:
* Add a DISTRIBUTE_ROLE to the staking contract.
* Require the caller of distribute() to have the DISTRIBUTE_ROLE
=> Staking: Addressing internal audit feedback

perfTest/token/erc721/ERC721Perf.t.sol, perfTest/token/erc721/ImmutableERC721ByIdPerf.t.sol, perfTest/token/erc721/ImmutableERC721ByQuantityPerf.t.sol, perfTest/token/erc721/ImmutableERC721V2ByQuantityPerf.t.sol
Added performance test to check the cost of calling `setNFTRoyaltyReceiverBatch`
=> Added changing royalty information perf test

contracts/staking/README.md
Whilst testing:
- I was not able to specify "10 gwei" as part of forge command -> updated to 10000000000 which worked
- Fixed file path
=> docs: Update README for DeployStakeHolder

script/staking/README.md
Add documentation about STAKEHOLDER_TYPE. Move common variables into the common section.
=> Resolve deficiencies in documentation

contracts/deployer/README.md
Add link to the audit report of OwnableCreate2Deployer and OwnableCreate3Deployer from the README.md file in the ./contracts/deployer directory.
=> Ownable Deployer: Add link to audit report

.github/workflows/publish.yaml
At present attestation is created for each individual file in the tar archive. 
This behaviour significantly slows down the integrity detection as each file's attestation needs to be verified separately.
This PR brings `contracts` NPM package in alignment with other NPM packages where we attest the package as a whole.
=> Attest NPM package as a whole.
